apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: huawei-cce-eip-vpc
  creationTimestamp: null
  labels:
    type: terraform
  name: huawei-cce-eip-vpc-new
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/zyc839/huawei-terraform-source.git
      path: cce-vpc-eip
      providerRef:
        name: huawei
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta2
      kind: Configuration
status: {}
